# jaeger/jaeger-docker-compose.yml
version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "5775:5775" # Jaeger agent port
      - "6831:6831/udp" # Jaeger agent port (UDP)
      - "5778:5778" # Jaeger HTTP port
      - "16686:16686" # Jaeger UI
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411

