# airflow/Dockerfile
FROM apache/airflow:2.6.2

USER airflow

# Install OpenTelemetry dependencies
RUN pip install --no-cache-dir \
    opentelemetry-api==1.15.0 \
    opentelemetry-sdk==1.15.0 \
    opentelemetry-instrumentation==0.39b0 \
    opentelemetry-exporter-jaeger==1.15.0
    #opentelemetry-instrumentation-airflow==0.37b0

RUN pip install apache-airflow-providers-apache-spark
RUN pip install opentelemetry-api opentelemetry-sdk opentelemetry-instrumentation opentelemetry-exporter-jaeger
# Set up your working directory
WORKDIR /opt/airflow

USER airflow
# Copy your DAGs and plugins
COPY dags/ ./dags/
#COPY plugins/ ./plugins/

